// DATA FOR SEARCH BOX

//STATEWISE DATA

  var stateNames = {

  "Alabama": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Alaska": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Arizona": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Arkansas": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "California": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Colarado": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Connecticut": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Delaware": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Florida": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Georgia": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Hawaii": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Idaho": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Illinois": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Indiana": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Iowa": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Kansas": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Kentucky": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Louisiana": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Maine": {
    "region-number": "1",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Maryland": {
    "region-number": "3",
    "region-name": "south",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Massacheusetts": {
    "region-number": "1",
    "region-name": "Northeast",
    "division-number": "1",
    "division-name": "New England",
  },
  "Michigan": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "3",
    "division-name": "East North Central",
  },
  "Minnesota": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "4",
    "division-name": "West North Central",
  },
  "Mississippi": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Missouiri": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "4",
    "division-name": "West North Central",
  },
  "Montana": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "8",
    "division-name": "Mountain",
  },
  "Nebraska": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "4",
    "division-name": "West North Central",
  },
  "Nevada": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "8",
    "division-name": "Mountain",
  },
  "New Hampshire": {
    "region-number": "1",
    "region-name": "Northeast",
    "division-number": "1",
    "division-name": "New England",
  },
  "New Jersey": {
    "region-number": "1",
    "region-name": "Northeast",
    "division-number": "2",
    "division-name": "Mid-Atlantic",
  },
  "New Mexico": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "8",
    "division-name": "Mountain",
  },
  "New York": {
    "region-number": "1",
    "region-name": "Northeast",
    "division-number": "2",
    "division-name": "Mid-Atlantic",
  },
  "North Carolina": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "5",
    "division-name": "South Atlantic",
  },
  "North Dakota": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "4",
    "division-name": "West North Central",
  },
  "Ohio": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "3",
    "division-name": "East North Central",
  },
  "Oklahoma": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "7",
    "division-name": "West South Central",
  },
  "Oregan": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "9",
    "division-name": "Pacific",
  },
  "Pennsylvania": {
    "region-number": "1",
    "region-name": "Northeast",
    "division-number": "2",
    "division-name": "Mid-Atlantic",
  },
  "South Carolina": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "5",
    "division-name": "South Atlantic",
  },
  "South Dakota": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "4",
    "division-name": "West North Central",
  },
  "Tennesse": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "6",
    "division-name": "East South Central",
  },
  "Texas": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "7",
    "division-name": "West South Central",
  },
  "Utah": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "8",
    "division-name": "Mountain",
  },
  "Vermont": {
    "region-number": "1",
    "region-name": "Northeast",
    "division-number": "1",
    "division-name": "New England",
  },
  "Virginia": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "5",
    "division-name": "South Atlantic",
  },
  "Washington": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "9",
    "division-name": "Pacific",
  },
  "Washington DC": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "5",
    "division-name": "South Atlantic",
  },
  "West Virginia": {
    "region-number": "3",
    "region-name": "South",
    "division-number": "5",
    "division-name": "South Atlantic",
  },
  "Wisconsin": {
    "region-number": "2",
    "region-name": "Midwest",
    "division-number": "3",
    "division-name": "East North Central",
  },
  "Wyoming": {
    "region-number": "4",
    "region-name": "West",
    "division-number": "8",
    "division-name": "Mountain",
  }
}
